const IMAGES = {
   logo: require("../assets/images/logo.png"),
   loading: require("../assets/images/loader2.png"),
   "icon-timer": require("../assets/images/icon-timer.png"),
   "icon-user-circle-gear": require("../assets/images/icon-user-circle-gear.png"),
   "icon-lightning": require("../assets/images/icon-lightning.png"),
   "icon-vibrate": require("../assets/images/icon-vibrate.png"),
   "icon-auth-phone": require("../assets/images/icon-auth-phone.png"),
   "icon-auth-phone-verify": require("../assets/images/icon-auth-phone-verify.png"),
   "icon-auth-fullname": require("../assets/images/icon-auth-fullname.png"),
   "icon-auth-email": require("../assets/images/icon-auth-email.png"),
   "icon-auth-pin": require("../assets/images/icon-auth-pin.png"),
   "icon-auth-bank": require("../assets/images/icon-auth-bank.png"),
   "icon-auth-check": require("../assets/images/icon-auth-check.png"),
   card: require("../assets/images/card.png"),
   // profile
   "icon-customer-support": require("../assets/images/icon-customer-support.png"),
   "icon-edit-profile": require("../assets/images/icon-edit-profile.png"),
   "icon-faq": require("../assets/images/icon-faq.png"),
   "icon-invite": require("../assets/images/icon-invite.png"),
   "icon-logout": require("../assets/images/icon-logout.png"),
   "icon-rate-us": require("../assets/images/icon-rate-us.png"),
   "icon-take-tour": require("../assets/images/icon-take-tour.png"),
   "icon-edit-detail": require("../assets/images/icon-edit-detail.png"),
   "icon-password": require("../assets/images/icon-password.png"),
   "icon-biometric": require("../assets/images/icon-biometric.png"),
   "icon-manage-account": require("../assets/images/icon-manage-account.png"),
   "icon-add": require("../assets/images/icon-add.png"),
   "icon-verify-account": require("../assets/images/icon-verify-account.png"),
   // bottom tabs
   "icon-tab-chat-active": require("../assets/images/icon-tab-chat-active.png"),
   "icon-tab-chat-inactive": require("../assets/images/icon-tab-chat-inactive.png"),
   "icon-tab-home-active": require("../assets/images/icon-tab-home-active.png"),
   "icon-tab-home-inactive": require("../assets/images/icon-tab-home-inactive.png"),
   "icon-tab-profile-active": require("../assets/images/icon-tab-profile-active.png"),
   "icon-tab-profile-inactive": require("../assets/images/icon-tab-profile-inactive.png"),
   "icon-tab-transaction-active": require("../assets/images/icon-tab-transaction-active.png"),
   "icon-tab-transaction-inactive": require("../assets/images/icon-tab-transaction-inactive.png"),
   //Home
   "icon-notification": require("../assets/images/icon-notification.png"),
   "icon-home-wallet": require("../assets/images/icon-home-wallet.png"),
   "icon-home-send": require("../assets/images/icon-home-send.png"),
   // "icon-biometric": require("../assets/images/icon-biometric.png"),
   // "icon-biometric": require("../assets/images/icon-biometric.png"),

   WalletIcon: require("../assets/images/WalletIcon.png"),
   slide1: require("../assets/images/slide_1.png"),
   slide2: require("../assets/images/slide_2.png"),
   newAvatar: require("../assets/images/newAvatar.png"),
   bells: require("../assets/images/bells.png"),
   Home: require("../assets/images/Home.png"),
   AddMoney: require("../assets/images/AddMoney.png"),
   SendMoney: require("../assets/images/SendMoney.png"),
   Notification: require("../assets/images/Notification.png")
};

export default IMAGES;
